### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by hhhaiai** [Lin152/myjson#1]
这个是什么系列的api，是否能动态访问本地资源，比如访问readme文件

**Comment by Lin152** [comment]
Github自带的东西，就是在Github上创建这样一个代码仓库，然后通过特定的API获取数据，能不能访问readme我也不清楚



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月13日(周四) 下午5:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Lin152/myjson] 请教个问题 (Issue #1)




 
这个是什么系列的api，是否能动态访问本地资源，比如访问readme文件
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hhhaiai** [comment]
嗯。好的，多谢了，这个貌似一个库+cdn实现的。  没细看 哈哈 。回头我琢磨下，明白了跟你同步哈
